/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.catalogosupermercado.frontend;
import com.mycompany.catalogosupermercado.estructuras.Grafo;
import javax.swing.JFileChooser;

/**
 *
 * @author mauricio
 */
public class PestañaInicio extends javax.swing.JFrame
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PestañaInicio.class.getName());
    private Grafo conexiones = new Grafo();
    /**
     * Creates new form PestañaInicio
     */
    public PestañaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCargarSucursales = new javax.swing.JButton();
        btnCargarAristas = new javax.swing.JButton();
        btnCargarProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cargar datos desde CSV");

        btnCargarSucursales.setText("Cargar Sucursales");
        btnCargarSucursales.addActionListener(this::btnCargarSucursalesActionPerformed);

        btnCargarAristas.setText("Cargar Aristas");
        btnCargarAristas.addActionListener(this::btnCargarAristasActionPerformed);

        btnCargarProductos.setText("Cargar Productos");
        btnCargarProductos.addActionListener(this::btnCargarProductosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarSucursales)
                    .addComponent(btnCargarAristas)
                    .addComponent(btnCargarProductos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarSucursales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarAristas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarProductos)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cargar CSV", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAristasActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVAristas(ruta);
                javax.swing.JOptionPane.showMessageDialog(this, "Se cargaron las Aristas.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de aristas: " + ex.getMessage(), "Error de Lectura", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarAristasActionPerformed

    private void btnCargarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSucursalesActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVSucursales(ruta);
                javax.swing.JOptionPane.showMessageDialog(this, "Se cargaron las Sucursales.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de sucursales:" + ex.getMessage(), "Error de Lectura", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarSucursalesActionPerformed

    private void btnCargarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductosActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVProductos(ruta);
                javax.swing.JOptionPane.showMessageDialog(this, "Se cargaron los Productos.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de productos: " + ex.getMessage(), "Error de Lectura", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PestañaInicio().setVisible(true));
    }
    
    private String cargarArchivos()
    {
        JFileChooser selector = new JFileChooser();

        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            return selector.getSelectedFile().getAbsolutePath();
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarAristas;
    private javax.swing.JButton btnCargarProductos;
    private javax.swing.JButton btnCargarSucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
