/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.catalogosupermercado.frontend;
import com.mycompany.catalogosupermercado.estructuras.Grafo;
import com.mycompany.catalogosupermercado.modelos.Producto;
import com.mycompany.catalogosupermercado.modelos.Sucursal;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mauricio
 */
public class PestañaInicio extends javax.swing.JFrame
{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PestañaInicio.class.getName());
    private Grafo conexiones = new Grafo();
    /**
     * Creates new form PestañaInicio
     */
    public PestañaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCargarSucursales = new javax.swing.JButton();
        btnCargarAristas = new javax.swing.JButton();
        btnCargarProductos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnBuscarNombreSeq = new javax.swing.JButton();
        btnBuscarCodigo = new javax.swing.JButton();
        btnBuscarRango = new javax.swing.JButton();
        btnBuscarCategoria = new javax.swing.JButton();
        btnListarNombre = new javax.swing.JButton();
        btnComparar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtConsolaGestorInventario = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxCriterio = new javax.swing.JComboBox<>();
        btnTransferir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsolaTransferencia = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnVerGrafo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();
        btnVerAVL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdSucursalVisualizar = new javax.swing.JTextField();
        btnVerB = new javax.swing.JButton();
        btnVerBMas = new javax.swing.JButton();
        btnVerTablaHash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cargar datos desde CSV");

        btnCargarSucursales.setText("Cargar Sucursales");
        btnCargarSucursales.addActionListener(this::btnCargarSucursalesActionPerformed);

        btnCargarAristas.setText("Cargar Aristas");
        btnCargarAristas.addActionListener(this::btnCargarAristasActionPerformed);

        btnCargarProductos.setText("Cargar Productos");
        btnCargarProductos.addActionListener(this::btnCargarProductosActionPerformed);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gestionar Inventario");

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(this::btnEliminarProductoActionPerformed);

        btnBuscarNombreSeq.setText("Buscar por Nombre Secuencial (Lista Enlazada)");
        btnBuscarNombreSeq.addActionListener(this::btnBuscarNombreSeqActionPerformed);

        btnBuscarCodigo.setText("Buscar por Código (Hash)");
        btnBuscarCodigo.addActionListener(this::btnBuscarCodigoActionPerformed);

        btnBuscarRango.setText("Buscar por Rango de Fechas (B)");
        btnBuscarRango.addActionListener(this::btnBuscarRangoActionPerformed);

        btnBuscarCategoria.setText("Buscar por Categorias (B+)");
        btnBuscarCategoria.addActionListener(this::btnBuscarCategoriaActionPerformed);

        btnListarNombre.setText("Listar por Nombre (AVL)");
        btnListarNombre.addActionListener(this::btnListarNombreActionPerformed);

        btnComparar.setText("Comparar Busqueda (Lista Enlazada - AVL)");
        btnComparar.addActionListener(this::btnCompararActionPerformed);

        jLabel7.setText("Productos:");

        jLabel9.setText("Busqueda:");

        txtConsolaGestorInventario.setEditable(false);
        txtConsolaGestorInventario.setColumns(20);
        txtConsolaGestorInventario.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCargarSucursales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargarAristas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarNombre))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarNombreSeq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRango)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCodigo))
                            .addComponent(btnComparar)
                            .addComponent(txtConsolaGestorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarSucursales)
                    .addComponent(btnCargarAristas)
                    .addComponent(btnCargarProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnEliminarProducto)
                    .addComponent(btnListarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarNombreSeq)
                    .addComponent(btnBuscarRango)
                    .addComponent(btnBuscarCategoria)
                    .addComponent(btnBuscarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComparar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsolaGestorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión", jPanel1);

        jLabel2.setText("Codigo del producto a transferir:");

        jLabel3.setText("ID de la Sucursal de origen:");

        jLabel4.setText("ID de la Sucursal de destino:");

        jLabel5.setText("Criterio de transferencia:");

        cbxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo", "Costo" }));
        cbxCriterio.addActionListener(this::cbxCriterioActionPerformed);

        btnTransferir.setText("Realizar Transferencia");
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);

        txtConsolaTransferencia.setEditable(false);
        txtConsolaTransferencia.setColumns(20);
        txtConsolaTransferencia.setRows(5);
        jScrollPane1.setViewportView(txtConsolaTransferencia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnTransferir)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(66, 66, 66)
                                .addComponent(cbxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 710, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnTransferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transferir", jPanel2);

        btnVerGrafo.setText("Ver Grafo Sucursales");
        btnVerGrafo.addActionListener(this::btnVerGrafoActionPerformed);

        jScrollPane2.setViewportView(lblImagen);

        btnVerAVL.setText("Ver Árbol AVL");
        btnVerAVL.addActionListener(this::btnVerAVLActionPerformed);

        jLabel6.setText("ID de Sucursal:");

        btnVerB.setText("Ver Árbol B");
        btnVerB.addActionListener(this::btnVerBActionPerformed);

        btnVerBMas.setText("Ver Árbol B+ ");
        btnVerBMas.addActionListener(this::btnVerBMasActionPerformed);

        btnVerTablaHash.setText("Ver Tabla Hash");
        btnVerTablaHash.addActionListener(this::btnVerTablaHashActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnVerGrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdSucursalVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerAVL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerBMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerTablaHash))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2)))
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerGrafo)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdSucursalVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerAVL)
                    .addComponent(btnVerB)
                    .addComponent(btnVerBMas)
                    .addComponent(btnVerTablaHash))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visualizar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarAristasActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVAristas(ruta);
                JOptionPane.showMessageDialog(this, "Se cargaron las Aristas.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada", JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de aristas: " + ex.getMessage(), "Error de Lectura", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarAristasActionPerformed

    private void btnCargarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSucursalesActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVSucursales(ruta);
                JOptionPane.showMessageDialog(this, "Se cargaron las Sucursales.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada",JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de sucursales:" + ex.getMessage(), "Error de Lectura", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarSucursalesActionPerformed

    private void btnCargarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductosActionPerformed
        String ruta = cargarArchivos();
        if (ruta != null)
        {
            if (!ruta.toLowerCase().endsWith(".csv"))
            {
                JOptionPane.showMessageDialog(this, "Error: El archivo seleccionado no es CSV. Por favor elige un archivo .csv", "Error de Formato", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try
            {
                conexiones.cargarCSVProductos(ruta);
                JOptionPane.showMessageDialog(this, "Se cargaron los Productos.\nSi había líneas con errores, fueron omitidas y guardadas en 'errors.log'.", "Carga Completada", JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al leer el archivo de productos: " + ex.getMessage(), "Error de Lectura", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarProductosActionPerformed

    private void cbxCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriterioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCriterioActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        try
        {
            String codigo = txtCodigoProducto.getText().trim();
            int idOrigen = Integer.parseInt(txtOrigen.getText().trim());
            int idDestino = Integer.parseInt(txtDestino.getText().trim());
            boolean esPorTiempo = cbxCriterio.getSelectedItem().toString().equals("Tiempo");
            Sucursal origen = conexiones.buscarSucursal(idOrigen);
            if (origen == null)
            {
                JOptionPane.showMessageDialog(this, "La sucursal de origen no está en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Producto producto = origen.getInventarioSucursal().buscarPorCodigo(codigo);
            if (producto == null)
            {
                JOptionPane.showMessageDialog(this, "No existe este producto en la sucursal de origen.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            txtConsolaTransferencia.setText("Calculando ruta...\n");
            origen.getInventarioSucursal().eliminarProducto(codigo);
            long inicio = System.nanoTime();
            String resultado = conexiones.realizarTransferencia(producto, idOrigen, idDestino, esPorTiempo);
            long fin = System.nanoTime();
            double tiempo = (fin - inicio) / 1000.0;
            txtConsolaTransferencia.setText("Tiempo de cálculo de ruta: " + tiempo + " us\n\n" + resultado);
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingresa números válidos para las IDs de las sucursales.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnVerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGrafoActionPerformed
        String archivoDot = "GrafoSucursales.dot";
        String archivoPng = "GrafoSucursales.png";
        conexiones.crearGrafico(archivoDot);
        generarImagenGraphviz(archivoDot, archivoPng);
        mostrarGraphviz(archivoPng);
    }//GEN-LAST:event_btnVerGrafoActionPerformed

    private void btnVerAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAVLActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(txtIdSucursalVisualizar.getText().trim());
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal == null)
            {
                JOptionPane.showMessageDialog(this, "La sucursal no está en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String archivoDot = "AvlSucursal_" + idSucursal + ".dot";
            String archivoPng = "AvlSucursal_" + idSucursal + ".png";
            sucursal.getInventarioSucursal().getArbolAVL().crearGrafico(archivoDot);
            generarImagenGraphviz(archivoDot, archivoPng);
            mostrarGraphviz(archivoPng);
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingresa un ID válido.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerAVLActionPerformed

    private void btnVerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(txtIdSucursalVisualizar.getText().trim());
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal == null)
            {
                JOptionPane.showMessageDialog(this, "La sucursal no está en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String archivoDot = "ArbolbSucursal_" + idSucursal + ".dot";
            String archivoPng = "ArbolbSucursal_" + idSucursal + ".png";
            sucursal.getInventarioSucursal().getArbolB().crearGrafico(archivoDot);
            generarImagenGraphviz(archivoDot, archivoPng);
            mostrarGraphviz(archivoPng);
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingresa un ID válido.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerBActionPerformed

    private void btnVerBMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBMasActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(txtIdSucursalVisualizar.getText().trim());
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal == null)
            {
                JOptionPane.showMessageDialog(this, "La sucursal no está en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String archivoDot = "ArbolBMasSucursal_" + idSucursal + ".dot";
            String archivoPng = "ArbolBMasSucursal_" + idSucursal + ".png";
            sucursal.getInventarioSucursal().getArbolBMas().crearGrafico(archivoDot);
            generarImagenGraphviz(archivoDot, archivoPng);
            mostrarGraphviz(archivoPng);
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingresa un ID válido.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerBMasActionPerformed

    private void btnVerTablaHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaHashActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(txtIdSucursalVisualizar.getText().trim());
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal == null)
            {
                JOptionPane.showMessageDialog(this, "La sucursal no está en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String archivoDot = "TablaHashSucursal_" + idSucursal + ".dot";
            String archivoPng = "TablaHashSucursal_" + idSucursal + ".png";
            
            sucursal.getInventarioSucursal().getTablaHash().crearGrafico(archivoDot);
            generarImagenGraphviz(archivoDot, archivoPng);
            mostrarGraphviz(archivoPng);
            
        } catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Ingresa un ID válido.", "Error", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerTablaHashActionPerformed

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String cat = JOptionPane.showInputDialog("Ingrese la Categoría:");
                if (cat != null && !cat.trim().isEmpty())
                {
                    long t0 = System.nanoTime();
                    String resultado = sucursal.getInventarioSucursal().getArbolBMas().buscarPorCategoria(cat);
                    double tiempo = (System.nanoTime() - t0) / 1000.0;
                    txtConsolaGestorInventario.setText("--- Búsqueda por Categoría (Árbol B+) ---\n");
                    txtConsolaGestorInventario.append("Tiempo de búsqueda: " + tiempo + " us\n\n");
                    txtConsolaGestorInventario.append(resultado);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Operación cancelada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String nombre = JOptionPane.showInputDialog("Nombre:");
                if (nombre == null || nombre.trim().isEmpty()) return;
                String codigo = JOptionPane.showInputDialog("Código de Barras:");
                String categoria = JOptionPane.showInputDialog("Categoría:");
                String fecha = JOptionPane.showInputDialog("Fecha (YYYY-MM-DD):");
                String marca = JOptionPane.showInputDialog("Marca:");
                double precio = Double.parseDouble(JOptionPane.showInputDialog("Precio (Q):"));
                int stock = Integer.parseInt(JOptionPane.showInputDialog("Stock:"));
                Producto producto = new Producto(nombre, codigo, categoria, fecha, marca, precio, stock);
                long t0 = System.nanoTime();
                boolean agregado = sucursal.getInventarioSucursal().agregarProducto(producto);
                double tiempo = (System.nanoTime() - t0) / 1000.0;
                txtConsolaGestorInventario.setText("--- Agregar Producto ---\n");
                if (agregado)
                {
                    txtConsolaGestorInventario.append("Estado: Producto agregado exitosamente en todas las estructuras.\n");
                    txtConsolaGestorInventario.append("Tiempo de inserción: " + tiempo + " us\n\n");
                    txtConsolaGestorInventario.append("Detalles: " + producto.getNombre() + " | Código: " + producto.getCodigoBarra());
                }
                else
                {
                    txtConsolaGestorInventario.append("Estado: Error al agregar.\n");
                    txtConsolaGestorInventario.append("Motivo: El código de barras '" + codigo + "' ya existe en el inventario de esta sucursal.");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Datos inválidos o números incorrectos.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {}
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String codigo = JOptionPane.showInputDialog("Ingrese el Código de Barras del producto a eliminar:");
                if (codigo != null && !codigo.trim().isEmpty())
                {
                    
                    long t0 = System.nanoTime();
                    boolean eliminado = sucursal.getInventarioSucursal().eliminarProducto(codigo);
                    double tiempo = (System.nanoTime() - t0) / 1000.0;
                    txtConsolaGestorInventario.setText("--- Eliminar Producto ---\n");
                    if (eliminado)
                    {
                        txtConsolaGestorInventario.append("Estado: Producto eliminado exitosamente de todas las estructuras.\n");
                        txtConsolaGestorInventario.append("Tiempo de eliminación: " + tiempo + " us\n");
                    }
                    else
                    {
                        txtConsolaGestorInventario.append("Estado: Error al eliminar.\n");
                        txtConsolaGestorInventario.append("Motivo: El producto con código '" + codigo + "' no existe en el inventario.");
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){}
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnListarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarNombreActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal para listar productos:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                long t0 = System.nanoTime();
                String resultado = sucursal.getInventarioSucursal().getArbolAVL().listarEnOrden();
                double tiempo = (System.nanoTime() - t0) / 1000.0;
                txtConsolaGestorInventario.setText("--- Listado Alfabético (Árbol AVL) ---\n");
                txtConsolaGestorInventario.append("Tiempo de listado: " + tiempo + " us\n\n");
                txtConsolaGestorInventario.append(resultado);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Operación cancelada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListarNombreActionPerformed

    private void btnBuscarNombreSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreSeqActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String nombre = JOptionPane.showInputDialog("Ingrese el Nombre exacto a buscar:");
                if (nombre != null && !nombre.trim().isEmpty())
                {
                    long t0 = System.nanoTime();
                    Producto producto = sucursal.getInventarioSucursal().buscarPorNombreSecuencial(nombre);
                    double tiempo = (System.nanoTime() - t0) / 1000.0;
                    txtConsolaGestorInventario.setText("--- Búsqueda por Nombre Secuencial (Lista Enlazada) ---\n");
                    txtConsolaGestorInventario.append("Tiempo de búsqueda: " + tiempo + " us\n\n");
                    if (producto != null)
                    {
                        txtConsolaGestorInventario.append("Producto Encontrado:\n");
                        txtConsolaGestorInventario.append(producto.getNombre() + " | Código: " + producto.getCodigoBarra() + " | Q" + producto.getPrecio() + " | Stock: " + producto.getStock());
                    }
                    else
                    {
                        txtConsolaGestorInventario.append("Producto no encontrado.");
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e){}
    }//GEN-LAST:event_btnBuscarNombreSeqActionPerformed

    private void btnBuscarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRangoActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String inicio = JOptionPane.showInputDialog("Fecha de Inicio (YYYY-MM-DD):");
                if (inicio != null && !inicio.trim().isEmpty())
                {
                    String fin = JOptionPane.showInputDialog("Fecha de Fin (YYYY-MM-DD):");
                    if (fin != null && !fin.trim().isEmpty())
                    {
                        long t0 = System.nanoTime();
                        String resultado = sucursal.getInventarioSucursal().getArbolB().mostrarEnRango(inicio, fin);
                        double tiempo = (System.nanoTime() - t0) / 1000.0;
                        txtConsolaGestorInventario.setText("--- Búsqueda por Rango de Fechas (Árbol B) ---\n");
                        txtConsolaGestorInventario.append("Tiempo de búsqueda: " + tiempo + " us\n\n");
                        txtConsolaGestorInventario.append(resultado);
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Operación cancelada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarRangoActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        try
        {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String codigo = JOptionPane.showInputDialog("Ingrese el Código de Barras:");
                if (codigo != null && !codigo.trim().isEmpty())
                {
                    long t0 = System.nanoTime();
                    Producto producto = sucursal.getInventarioSucursal().buscarPorCodigo(codigo);
                    double tiempo = (System.nanoTime() - t0) / 1000.0;
                    txtConsolaGestorInventario.setText("--- Búsqueda por Código (Tabla Hash) ---\n");
                    txtConsolaGestorInventario.append("Tiempo de búsqueda: " + tiempo + " us\n\n");
                    if (producto != null)
                    {
                        txtConsolaGestorInventario.append("Producto Encontrado:\n");
                        txtConsolaGestorInventario.append(producto.getNombre() + " | Marca: " + producto.getMarca() + " | Stock: " + producto.getStock() + " | Q" + producto.getPrecio());
                    }
                    else
                    {
                        txtConsolaGestorInventario.append("Producto no encontrado.");
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Operación cancelada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        try {
            int idSucursal = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el ID de la Sucursal para la comparación:"));
            Sucursal sucursal = conexiones.buscarSucursal(idSucursal);
            if (sucursal != null)
            {
                String reporte = sucursal.getInventarioSucursal().compararBusquedas(25, 5);
                txtConsolaGestorInventario.setText(reporte); // Imprime el String generado en tu método compararBusquedas
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sucursal no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "ID de sucursal inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Operación cancelada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PestañaInicio().setVisible(true));
    }
    
    private String cargarArchivos()
    {
        JFileChooser selector = new JFileChooser();
        if (selector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            return selector.getSelectedFile().getAbsolutePath();
        }
        return null;
    }
    
    private void generarImagenGraphviz(String rutaDot, String rutaPng)
    {
        try
        {
            ProcessBuilder pb = new ProcessBuilder("dot", "-Tpng", rutaDot, "-o", rutaPng);
            pb.redirectErrorStream(true);
            Process proceso = pb.start();
            proceso.waitFor();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error al ejecutar Graphviz.\n¿Tienes Graphviz instalado y en el PATH de Windows?\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void mostrarGraphviz(String rutaPng) 
    {
        File archivo = new java.io.File(rutaPng);
        if (archivo.exists())
        {
            ImageIcon imagen = new ImageIcon(rutaPng);
            imagen.getImage().flush();
            lblImagen.setIcon(imagen);
            lblImagen.repaint();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se encontró la imagen generada.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarCategoria;
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnBuscarNombreSeq;
    private javax.swing.JButton btnBuscarRango;
    private javax.swing.JButton btnCargarAristas;
    private javax.swing.JButton btnCargarProductos;
    private javax.swing.JButton btnCargarSucursales;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListarNombre;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVerAVL;
    private javax.swing.JButton btnVerB;
    private javax.swing.JButton btnVerBMas;
    private javax.swing.JButton btnVerGrafo;
    private javax.swing.JButton btnVerTablaHash;
    private javax.swing.JComboBox<String> cbxCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextArea txtConsolaGestorInventario;
    private javax.swing.JTextArea txtConsolaTransferencia;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtIdSucursalVisualizar;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables

}
